require 'embraces-nested-attributes/version'
require 'embraces-nested-attributes/relation_extensions'
require 'embraces-nested-attributes/assoc_ordering'
require 'embraces-nested-attributes/assume_destroy'
require 'embraces-nested-attributes/many_to_many'
require 'embraces-nested-attributes/nillable_find'
require 'embraces-nested-attributes/polymorphic_build'
